### ISSUE TITLE
[py38 + mac] OSError: cannot open resource 😭 

### ISSUE THREAD

**Issue by RRRoger** [yihong0618/GitHubPoster#27]
```bash
Traceback (most recent call last):
  File "/Users/xxxxxxxxx/opt/miniconda3/envs/py38/bin/github_poster", line 8, in <module>
    sys.exit(main())
  File "/Users/xxxxxxxxx/opt/miniconda3/envs/py38/lib/python3.8/site-packages/github_poster/cli.py", line 118, in main
    s.make_skyline()
  File "/Users/xxxxxxxxx/opt/miniconda3/envs/py38/lib/python3.8/site-packages/github_poster/skyline/skyline.py", line 115, in make_skyline
    skyline_info_card = self._make_skyline_card(text_info)
  File "/Users/xxxxxxxxx/opt/miniconda3/envs/py38/lib/python3.8/site-packages/github_poster/skyline/skyline.py", line 76, in _make_skyline_card
    w, h = measure_text(FONT, TEXT)
  File "/Users/xxxxxxxxx/opt/miniconda3/envs/py38/lib/python3.8/site-packages/sdf/text.py", line 19, in measure_text
    font = ImageFont.truetype(name, 96)
  File "/Users/xxxxxxxxx/opt/miniconda3/envs/py38/lib/python3.8/site-packages/PIL/ImageFont.py", line 855, in truetype
    return freetype(font)
  File "/Users/xxxxxxxxx/opt/miniconda3/envs/py38/lib/python3.8/site-packages/PIL/ImageFont.py", line 852, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/Users/xxxxxxxxx/opt/miniconda3/envs/py38/lib/python3.8/site-packages/PIL/ImageFont.py", line 211, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by RRRoger** [comment]
# And the same error in centos

```bash
Traceback (most recent call last):
  File "/root/miniconda3/envs/py38/bin/github_poster", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/github_poster/cli.py", line 118, in main
    s.make_skyline()
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/github_poster/skyline/skyline.py", line 115, in make_skyline
    skyline_info_card = self._make_skyline_card(text_info)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/github_poster/skyline/skyline.py", line 76, in _make_skyline_card
    w, h = measure_text(FONT, TEXT)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/sdf/text.py", line 19, in measure_text
    font = ImageFont.truetype(name, 96)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/PIL/ImageFont.py", line 855, in truetype
    return freetype(font)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/PIL/ImageFont.py", line 852, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/PIL/ImageFont.py", line 211, in __init__
    self.font = core.getfont(
OSError: cannot open resource
```

**Comment by yihong0618** [comment]
@RRRoger 

That's a bug by pip.

Two ways to solve this by now.

1. copy the font dir to your `excute` dir
2. use clone way `python3 -m github_poster github --user_name yihong0618 --with-skyline`

I will try to fix this later

**Comment by RRRoger** [comment]
ok, it works , thanks so much, 😄

**Comment by yihong0618** [comment]
Cool, but the I found that the font location is hard...

So let's keep this issue open until we find a better solution

**Comment by RRRoger** [comment]
Maybe we can use ENV variable.

or  use the absolute path in different OS system

or this Solution: https://stackoverflow.com/questions/47694421/pil-issue-oserror-cannot-open-resource

**Comment by yihong0618** [comment]
@RRRoger 

Fixed can you test with pip?


```shell
pip3 install -U github_poster
```

**Comment by RRRoger** [comment]
Hi, i have used the command `pip3 install -U github_poster` several times. 

But it doesn't seem to be the latest version.

It raised the same error like before. :(

**Comment by yihong0618** [comment]
@RRRoger  Sorry, my fault 
Can you try again?

**Comment by RRRoger** [comment]
Yes, it works finally. I use pip with the official source.

```bash
pip install -U github_poster -i https://pypi.org/simple
```

**Comment by yihong0618** [comment]
Thanks
