### ISSUE TITLE
win10 python3

### ISSUE THREAD

**Issue by netoearth** [yihong0618/GitHubPoster#8]
Traceback (most recent call last):
  File "F:\github\GitHubPoster\cli.py", line 11, in <module>
    from loader import (
  File "F:\github\GitHubPoster\loader\__init__.py", line 5, in <module>
    from .github_loader import GitHubLoader
  File "F:\github\GitHubPoster\loader\github_loader.py", line 1, in <module>
    from parser import GitHubParser
ImportError: cannot import name 'GitHubParser' from 'parser' (unknown location)

**Comment by yihong0618** [comment]
请问是在 GitHubPoster 根目录执行么？

**Comment by netoearth** [comment]
是的，pip install已经安装完毕了，奇怪还错找不到组件

**Comment by yihong0618** [comment]
主分支是 main 不是 master.

**Comment by yihong0618** [comment]
@netoearth 我尝试修改了下，请测试。

**Comment by netoearth** [comment]
感谢！已解决
